package Data;
// Generated Jan 6, 2012 2:21:37 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BookSourceForOrder generated by hbm2java
 */
public class BookSourceForOrder  implements java.io.Serializable {


     private long id;
     private CustomerOrder customerOrder;
     private Institution institution;
     private Integer expectedNumberOfBooks;
     private Integer numberOfReceivedBooks;
     private Date dateCreated;
     private Set<OrderBook> orderBooks = new HashSet<OrderBook>(0);

    public BookSourceForOrder() {
    }

	
    public BookSourceForOrder(long id, CustomerOrder customerOrder, Institution institution, Date dateCreated) {
        this.id = id;
        this.customerOrder = customerOrder;
        this.institution = institution;
        this.dateCreated = dateCreated;
    }
    public BookSourceForOrder(long id, CustomerOrder customerOrder, Institution institution, Integer expectedNumberOfBooks, Integer numberOfReceivedBooks, Date dateCreated, Set<OrderBook> orderBooks) {
       this.id = id;
       this.customerOrder = customerOrder;
       this.institution = institution;
       this.expectedNumberOfBooks = expectedNumberOfBooks;
       this.numberOfReceivedBooks = numberOfReceivedBooks;
       this.dateCreated = dateCreated;
       this.orderBooks = orderBooks;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public CustomerOrder getCustomerOrder() {
        return this.customerOrder;
    }
    
    public void setCustomerOrder(CustomerOrder customerOrder) {
        this.customerOrder = customerOrder;
    }
    public Institution getInstitution() {
        return this.institution;
    }
    
    public void setInstitution(Institution institution) {
        this.institution = institution;
    }
    public Integer getExpectedNumberOfBooks() {
        return this.expectedNumberOfBooks;
    }
    
    public void setExpectedNumberOfBooks(Integer expectedNumberOfBooks) {
        this.expectedNumberOfBooks = expectedNumberOfBooks;
    }
    public Integer getNumberOfReceivedBooks() {
        return this.numberOfReceivedBooks;
    }
    
    public void setNumberOfReceivedBooks(Integer numberOfReceivedBooks) {
        this.numberOfReceivedBooks = numberOfReceivedBooks;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Set<OrderBook> getOrderBooks() {
        return this.orderBooks;
    }
    
    public void setOrderBooks(Set<OrderBook> orderBooks) {
        this.orderBooks = orderBooks;
    }




}


