package Data;
// Generated Jan 6, 2012 2:21:37 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BookScanner generated by hbm2java
 */
public class BookScanner  implements java.io.Serializable {


     private long id;
     private FixedLocation fixedLocation;
     private Serializable bookScannerCode;
     private Serializable name;
     private Serializable barcode;
     private Date moveInDate;
     private Long prevFixedLocationId;
     private Date prevMoveInDate;
     private Long createdPersonId;
     private Date dateCreated;
     private Set<OrderBook> orderBooks = new HashSet<OrderBook>(0);

    public BookScanner() {
    }

	
    public BookScanner(long id, Serializable bookScannerCode, Date dateCreated) {
        this.id = id;
        this.bookScannerCode = bookScannerCode;
        this.dateCreated = dateCreated;
    }
    public BookScanner(long id, FixedLocation fixedLocation, Serializable bookScannerCode, Serializable name, Serializable barcode, Date moveInDate, Long prevFixedLocationId, Date prevMoveInDate, Long createdPersonId, Date dateCreated, Set<OrderBook> orderBooks) {
       this.id = id;
       this.fixedLocation = fixedLocation;
       this.bookScannerCode = bookScannerCode;
       this.name = name;
       this.barcode = barcode;
       this.moveInDate = moveInDate;
       this.prevFixedLocationId = prevFixedLocationId;
       this.prevMoveInDate = prevMoveInDate;
       this.createdPersonId = createdPersonId;
       this.dateCreated = dateCreated;
       this.orderBooks = orderBooks;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public FixedLocation getFixedLocation() {
        return this.fixedLocation;
    }
    
    public void setFixedLocation(FixedLocation fixedLocation) {
        this.fixedLocation = fixedLocation;
    }
    public Serializable getBookScannerCode() {
        return this.bookScannerCode;
    }
    
    public void setBookScannerCode(Serializable bookScannerCode) {
        this.bookScannerCode = bookScannerCode;
    }
    public Serializable getName() {
        return this.name;
    }
    
    public void setName(Serializable name) {
        this.name = name;
    }
    public Serializable getBarcode() {
        return this.barcode;
    }
    
    public void setBarcode(Serializable barcode) {
        this.barcode = barcode;
    }
    public Date getMoveInDate() {
        return this.moveInDate;
    }
    
    public void setMoveInDate(Date moveInDate) {
        this.moveInDate = moveInDate;
    }
    public Long getPrevFixedLocationId() {
        return this.prevFixedLocationId;
    }
    
    public void setPrevFixedLocationId(Long prevFixedLocationId) {
        this.prevFixedLocationId = prevFixedLocationId;
    }
    public Date getPrevMoveInDate() {
        return this.prevMoveInDate;
    }
    
    public void setPrevMoveInDate(Date prevMoveInDate) {
        this.prevMoveInDate = prevMoveInDate;
    }
    public Long getCreatedPersonId() {
        return this.createdPersonId;
    }
    
    public void setCreatedPersonId(Long createdPersonId) {
        this.createdPersonId = createdPersonId;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Set<OrderBook> getOrderBooks() {
        return this.orderBooks;
    }
    
    public void setOrderBooks(Set<OrderBook> orderBooks) {
        this.orderBooks = orderBooks;
    }




}


