package Data;
// Generated Jan 6, 2012 2:21:37 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CustomerOrder generated by hbm2java
 */
public class CustomerOrder  implements java.io.Serializable {


     private long id;
     private Customer customer;
     private Serializable description;
     private Integer numberOfBooks;
     private Serializable folderName;
     private Date dateCreated;
     private Set<BookSourceForOrder> bookSourceForOrders = new HashSet<BookSourceForOrder>(0);
     private Set<Project> projects = new HashSet<Project>(0);

    public CustomerOrder() {
    }

	
    public CustomerOrder(long id, Customer customer, Date dateCreated) {
        this.id = id;
        this.customer = customer;
        this.dateCreated = dateCreated;
    }
    public CustomerOrder(long id, Customer customer, Serializable description, Integer numberOfBooks, Serializable folderName, Date dateCreated, Set<BookSourceForOrder> bookSourceForOrders, Set<Project> projects) {
       this.id = id;
       this.customer = customer;
       this.description = description;
       this.numberOfBooks = numberOfBooks;
       this.folderName = folderName;
       this.dateCreated = dateCreated;
       this.bookSourceForOrders = bookSourceForOrders;
       this.projects = projects;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Serializable getDescription() {
        return this.description;
    }
    
    public void setDescription(Serializable description) {
        this.description = description;
    }
    public Integer getNumberOfBooks() {
        return this.numberOfBooks;
    }
    
    public void setNumberOfBooks(Integer numberOfBooks) {
        this.numberOfBooks = numberOfBooks;
    }
    public Serializable getFolderName() {
        return this.folderName;
    }
    
    public void setFolderName(Serializable folderName) {
        this.folderName = folderName;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Set<BookSourceForOrder> getBookSourceForOrders() {
        return this.bookSourceForOrders;
    }
    
    public void setBookSourceForOrders(Set<BookSourceForOrder> bookSourceForOrders) {
        this.bookSourceForOrders = bookSourceForOrders;
    }
    public Set<Project> getProjects() {
        return this.projects;
    }
    
    public void setProjects(Set<Project> projects) {
        this.projects = projects;
    }




}


