package Data;
// Generated Jan 6, 2012 2:21:37 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
public class Project  implements java.io.Serializable {


     private long id;
     private CustomerOrder customerOrder;
     private Serializable description;
     private Serializable bookPlate;
     private byte[] binaryContent;
     private Integer lengthOfBinaryContent;
     private Serializable fileName;
     private Date fileCreationDateTime;
     private Serializable folderName;
     private Date dateCreated;
     private Boolean isFinalizedProject;
     private Set<OrderBook> orderBooks = new HashSet<OrderBook>(0);

    public Project() {
    }

	
    public Project(long id, CustomerOrder customerOrder, Serializable description, Serializable folderName, Date dateCreated) {
        this.id = id;
        this.customerOrder = customerOrder;
        this.description = description;
        this.folderName = folderName;
        this.dateCreated = dateCreated;
    }
    public Project(long id, CustomerOrder customerOrder, Serializable description, Serializable bookPlate, byte[] binaryContent, Integer lengthOfBinaryContent, Serializable fileName, Date fileCreationDateTime, Serializable folderName, Date dateCreated, Boolean isFinalizedProject, Set<OrderBook> orderBooks) {
       this.id = id;
       this.customerOrder = customerOrder;
       this.description = description;
       this.bookPlate = bookPlate;
       this.binaryContent = binaryContent;
       this.lengthOfBinaryContent = lengthOfBinaryContent;
       this.fileName = fileName;
       this.fileCreationDateTime = fileCreationDateTime;
       this.folderName = folderName;
       this.dateCreated = dateCreated;
       this.isFinalizedProject = isFinalizedProject;
       this.orderBooks = orderBooks;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public CustomerOrder getCustomerOrder() {
        return this.customerOrder;
    }
    
    public void setCustomerOrder(CustomerOrder customerOrder) {
        this.customerOrder = customerOrder;
    }
    public Serializable getDescription() {
        return this.description;
    }
    
    public void setDescription(Serializable description) {
        this.description = description;
    }
    public Serializable getBookPlate() {
        return this.bookPlate;
    }
    
    public void setBookPlate(Serializable bookPlate) {
        this.bookPlate = bookPlate;
    }
    public byte[] getBinaryContent() {
        return this.binaryContent;
    }
    
    public void setBinaryContent(byte[] binaryContent) {
        this.binaryContent = binaryContent;
    }
    public Integer getLengthOfBinaryContent() {
        return this.lengthOfBinaryContent;
    }
    
    public void setLengthOfBinaryContent(Integer lengthOfBinaryContent) {
        this.lengthOfBinaryContent = lengthOfBinaryContent;
    }
    public Serializable getFileName() {
        return this.fileName;
    }
    
    public void setFileName(Serializable fileName) {
        this.fileName = fileName;
    }
    public Date getFileCreationDateTime() {
        return this.fileCreationDateTime;
    }
    
    public void setFileCreationDateTime(Date fileCreationDateTime) {
        this.fileCreationDateTime = fileCreationDateTime;
    }
    public Serializable getFolderName() {
        return this.folderName;
    }
    
    public void setFolderName(Serializable folderName) {
        this.folderName = folderName;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Boolean getIsFinalizedProject() {
        return this.isFinalizedProject;
    }
    
    public void setIsFinalizedProject(Boolean isFinalizedProject) {
        this.isFinalizedProject = isFinalizedProject;
    }
    public Set<OrderBook> getOrderBooks() {
        return this.orderBooks;
    }
    
    public void setOrderBooks(Set<OrderBook> orderBooks) {
        this.orderBooks = orderBooks;
    }




}


