package Data;
// Generated Jan 6, 2012 2:21:37 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * WorkflowStep generated by hbm2java
 */
public class WorkflowStep  implements java.io.Serializable {


     private long id;
     private Serializable code;
     private Serializable name;
     private Serializable emailServerName;
     private Serializable fromEmailAddress;
     private Serializable toEmailAddress;
     private Serializable defaultEmailSubject;
     private Serializable defaultEmailBody;
     private Date dateCreated;
     private Set<OrderBook> orderBooks = new HashSet<OrderBook>(0);

    public WorkflowStep() {
    }

	
    public WorkflowStep(long id, Serializable code) {
        this.id = id;
        this.code = code;
    }
    public WorkflowStep(long id, Serializable code, Serializable name, Serializable emailServerName, Serializable fromEmailAddress, Serializable toEmailAddress, Serializable defaultEmailSubject, Serializable defaultEmailBody, Date dateCreated, Set<OrderBook> orderBooks) {
       this.id = id;
       this.code = code;
       this.name = name;
       this.emailServerName = emailServerName;
       this.fromEmailAddress = fromEmailAddress;
       this.toEmailAddress = toEmailAddress;
       this.defaultEmailSubject = defaultEmailSubject;
       this.defaultEmailBody = defaultEmailBody;
       this.dateCreated = dateCreated;
       this.orderBooks = orderBooks;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Serializable getCode() {
        return this.code;
    }
    
    public void setCode(Serializable code) {
        this.code = code;
    }
    public Serializable getName() {
        return this.name;
    }
    
    public void setName(Serializable name) {
        this.name = name;
    }
    public Serializable getEmailServerName() {
        return this.emailServerName;
    }
    
    public void setEmailServerName(Serializable emailServerName) {
        this.emailServerName = emailServerName;
    }
    public Serializable getFromEmailAddress() {
        return this.fromEmailAddress;
    }
    
    public void setFromEmailAddress(Serializable fromEmailAddress) {
        this.fromEmailAddress = fromEmailAddress;
    }
    public Serializable getToEmailAddress() {
        return this.toEmailAddress;
    }
    
    public void setToEmailAddress(Serializable toEmailAddress) {
        this.toEmailAddress = toEmailAddress;
    }
    public Serializable getDefaultEmailSubject() {
        return this.defaultEmailSubject;
    }
    
    public void setDefaultEmailSubject(Serializable defaultEmailSubject) {
        this.defaultEmailSubject = defaultEmailSubject;
    }
    public Serializable getDefaultEmailBody() {
        return this.defaultEmailBody;
    }
    
    public void setDefaultEmailBody(Serializable defaultEmailBody) {
        this.defaultEmailBody = defaultEmailBody;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Set<OrderBook> getOrderBooks() {
        return this.orderBooks;
    }
    
    public void setOrderBooks(Set<OrderBook> orderBooks) {
        this.orderBooks = orderBooks;
    }




}


